name: flower_ai_api
description: "Flower API - A plant recognition app on HF"
publish_to: 'none'
version: 0.7.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  http: ^1.3.0
  image: ^4.5.3
  image_picker: ^1.1.2
  tflite_flutter: ^0.11.0
  google_fonts: ^6.1.0
  provider: ^6.1.1
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.8.0
  share_plus: ^10.1.4
  path_provider: ^2.1.2
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
  - family: Sora
    fonts:
      - asset: assets/Sora-Regular.ttf
      - asset: assets/Sora-Bold.ttf
        weight: 700
      - asset: assets/Sora-Light.ttf
        weight: 300
  
  assets:
    - assets/icon/icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
